# Generated by Django 4.2.7 on 2023-11-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cartid',
            new_name='cart_id',
        ),
    ]
